# This is free and unencumbered software released into the public domain.

name: build

on:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: arm64
            runner: ubuntu-24.04-arm
          - arch: x64
            runner: ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          if: github.event_name == 'release'
            runCmd: zig build -Dversion=${{ github.ref_name }}
          if: github.event_name != 'release'
            runCmd: zig build

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ matrix.arch }}
          path: zig-out

      - name: Publish
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} zig-out/*.zip
